from __future__ import annotations

import re
from typing import Dict

from app.models import Candidate, NormalizedOrganization


TRANSLIT_MAP: Dict[str, str] = {
    "а": "a", "б": "b", "в": "v", "г": "g", "д": "d", "е": "e", "ё": "e", "ж": "zh", "з": "z",
    "и": "i", "й": "i", "к": "k", "л": "l", "м": "m", "н": "n", "о": "o", "п": "p", "р": "r",
    "с": "s", "т": "t", "у": "u", "ф": "f", "х": "kh", "ц": "ts", "ч": "ch", "ш": "sh", "щ": "shch",
    "ъ": "", "ы": "y", "ь": "", "э": "e", "ю": "yu", "я": "ya",
}


class TranslitFallbackSource:
    def build(self, org: NormalizedOrganization) -> Candidate:
        text = self.transliterate(org.normalized)
        return Candidate(
            organization_ru_raw=org.raw,
            organization_ru_normalized=org.normalized,
            candidate_text=text,
            source="translit_fallback",
            notes=["Generated by fallback transliteration"],
        )

    def transliterate(self, text: str) -> str:
        result = []
        for ch in text.lower():
            result.append(TRANSLIT_MAP.get(ch, ch))
        joined = "".join(result)
        joined = re.sub(r"\bim\.\b", "named after", joined)
        joined = re.sub(r"\s+", " ", joined).strip()
        return " ".join(w.capitalize() for w in joined.split())
